# Generated by Django 4.0.3 on 2022-03-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='query_id',
            field=models.IntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
