# Generated by Django 4.0.3 on 2022-03-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_milestone_query_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='query_id',
            field=models.IntegerField(default=5, editable=False),
        ),
    ]
