# Generated by Django 4.0.3 on 2022-03-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='project',
        ),
    ]
