# Generated by Django 4.0.3 on 2022-03-11 19:33

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_milestone_project'),
        ('files', '0003_remove_file_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to=files.models.get_project_directory),
        ),
    ]
