# Generated by Django 4.0.3 on 2022-03-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_rev_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rev',
            name='revision',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
