# Generated by Django 4.0.3 on 2022-03-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_rev_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='query_id',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
