# Generated by Django 4.0.3 on 2022-03-12 16:21

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_file_query_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='rev',
            name='extension',
        ),
        migrations.AddField(
            model_name='file',
            name='mimetype',
            field=models.CharField(default='application/json', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rev',
            name='mimetype',
            field=models.CharField(default='application/json', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=files.models.get_project_directory),
        ),
        migrations.AlterField(
            model_name='rev',
            name='file',
            field=models.FileField(upload_to=files.models.get_rev_directory),
        ),
    ]
