# Generated by Django 4.0.3 on 2022-03-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_remove_file_extension_remove_rev_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='date_changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rev',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rev',
            name='date_changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
