# Generated by Django 4.0.3 on 2022-03-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_alter_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rev',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rev',
            name='date_changed',
            field=models.DateTimeField(null=True),
        ),
    ]
