# Generated by Django 4.0.3 on 2022-03-13 00:03

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_rename_date_added_file_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=500, upload_to=files.models.get_project_directory),
        ),
    ]
